/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRVB2RG1YRWZFK1JqSUcwU1ZKWXJXMFpKOW1BS3hxL2tTRm9YUEk4R3BWZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMGFYMlRlNVlxQytQSGxLNVRDWEZQbXRHTU1LcGIwcnFtQ0NaK0NBRTBrST0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ1T3FLbTU5QWc3NWpjRm1LY3g4bitlQ2tuR1RiaHYxM1g5NjNrWGJXakVnPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJpZ3N0L3BvbitiT0VwYVdtUU16WnMxMHpuVGJhZGlqVEVLa0duNjF0RXlFPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InFFWHlsMXgrVHdGMFZnck9GWVI0UitteThNVm9IUlJrYWtNaWJMcW1tMHc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImFLU1lKalhQSnJtTkVnbVBKOWNDZmE0VUFvOFlxRlo3aDFieXJVdER1bGM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0VMQ0JReDhtR2NHam1KdkllUU5FRkpuYk1mSzdQWm9SNW0rbmtLYnFYQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTlNVS3Y4aDY2dkRQMkFEUzBSZ0Q1NmEzalY2WFZiS2lpSkJMUzZ4TGlYTT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik54b0MwWFlUeUprYlNubXpLSVZGbEdlclJiWVBwYWczcEU4T0dKbm5LVFo1Znp3TnhYQlBpTVBzR0x4S3hvQmdSdmFEQmcvZ0wwc3BaejM4T3Fud2hnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTk1LCJhZHZTZWNyZXRLZXkiOiJpNkh5VERvTGFsQno5dHlkZDVraHJUcXFYa2U3MStjWnJOKzFrY3J6cXRFPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc0NjQ5NjkwNkBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI3M0ZBRjJBMTVEQ0M4NjYxOUY0RjM5NDM4ODlBNUE0NSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzIxMDQzMTE4fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3NDY0OTY5MDZAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiRDIxMzI3RUFFNkQ0NERGRDJFODgzNDQ1NzM3NThGMDUifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyMTA0MzEyMH1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiMGRZNTVGTHZTcjJqck1UOXlTWWQ5QSIsInBob25lSWQiOiI4MWVlZjQxYy1iMTQ1LTRiODctOTEwOS0yNjQyNTQ1NTkxN2IiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY2lxUE51eFRMVUI0UllHM0VreEFsUDAwUzBrPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlV4bjF4RnB0Mzl3YmxzanM4TzZqWDFpcnkyQT0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiIySzFYOVJRUiIsIm1lIjp7ImlkIjoiMjU0NzQ2NDk2OTA2Ojc5QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IvCdk77wnZO38J2TtPCdk7fwnZO48J2UgPCdk7df8J2UgvCdk67wnZO9X/Cdk6/wnZOq8J2TtvCdk7LwnZO18J2TsvCdk6rwnZO7In0sImFjY291bnQiOnsiZGV0YWlscyI6IkNNT1J6SzRIRUp1UjFMUUdHQmtnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiI2cGhDb0R2ZWx6YzhUby9MS0NiMEhKRW5tWTRqZm5YN1VVelIwOCtxeFRnPSIsImFjY291bnRTaWduYXR1cmUiOiI3b2hmYlVnaDlzaHJDWWppZ1FtS1NBU1BBcGQzaDhpQm1uQ25TeWRnZVJiM001RjkrTXZ3Zm40N2VOaWVKQXRiT3JiS3E5eDFQR1hWdWlvNlg2OFpEZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiVFZaRzhEQktuYXNBK1EzMWxZMG5PU2VEYkpjTWNTQkp4dWZ5NmpYNDlUVTdWRWR5aGpoeW42L1h4dHlmdE5OcWdLUEtFOHlISStPOE4rTVp2S0craXc9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3NDY0OTY5MDY6NzlAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCZXFZUXFBNzNwYzNQRTZQeXlnbTlCeVJKNW1PSTM1MSsxRk0wZFBQcXNVNCJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTcyMTA0MzExMiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFGRUoifQ==';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'fortunatus';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '254114018035';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DREADED';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'true';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'typing';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'true';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session
};
